name: Gatling Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd ./javascript
          npm install

      - name: Run Gatling load test
        run: |
          cd ./javascript
          npm run build
          node ./src/purchaseTicket-load.js

      - name: Archive Gatling results
        if: always()
        run: |
          mkdir -p reports
          cp -R ./javascript/results/* reports/
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: gatling-results
          path: reports
